// Copyright (c) MUXUE1230. All rights reserved.
// Modifications Copyright (c) 2026 PCL N contributors.
// Licensed under the Apache License, Version 2.0.

using System;
using System.Threading;
using System.Threading.Tasks;

namespace PCL.Core.Utils.Threading;

// Partly generated by o4-mini-high (20250709)

/// <summary>
/// 使用两个线程池的调度器，分为 CPU 线程池和 IO 线程池，分别负责 CPU 密集型任务和 IO 密集型任务
/// </summary>
public sealed class DualThreadPool : IDisposable
{
    /// <summary>
    /// 两线程池分别计算的最大线程数
    /// </summary>
    public int MaxThread { get; }

    private readonly SemaphoreSlim _ioGate;
    private readonly SemaphoreSlim _cpuGate;
    private readonly CancellationTokenSource _cts = new();

    /// <summary>
    /// 初始化 <see cref="DualThreadPool"/> 实例
    /// </summary>
    /// <param name="maxThread">参考 <see cref="MaxThread"/>，最小为 1</param>
    /// <exception cref="ArgumentOutOfRangeException">最大线程数小于 1</exception>
    public DualThreadPool(int maxThread)
    {
        ArgumentOutOfRangeException.ThrowIfLessThan(maxThread, 1);

        MaxThread = maxThread;

        _ioGate = new SemaphoreSlim(maxThread, maxThread);
        _cpuGate = new SemaphoreSlim(maxThread, maxThread);
    }

    /// <summary>
    /// 提交一段 IO 密集工作
    /// </summary>
    public Task QueueIo(Action work) => QueueAsync(_ioGate, work);

    /// <summary>
    /// 提交一段异步 IO 密集工作
    /// </summary>
    public Task QueueIo(Func<Task> work) => QueueAsync(_ioGate, work);

    /// <summary>
    /// 提交一段 CPU 密集工作
    /// </summary>
    public Task QueueCpu(Action work) => QueueAsync(_cpuGate, work);

    /// <summary>
    /// 提交一段异步 CPU 密集工作
    /// </summary>
    public Task QueueCpu(Func<Task> work) => QueueAsync(_cpuGate, work);

    /// <summary>
    /// 取消所有正在执行的工作
    /// </summary>
    public void CancelAll() => _cts.Cancel();

    private Task QueueAsync(SemaphoreSlim gate, Action work)
    {
        ArgumentNullException.ThrowIfNull(work);
        return QueueAsync(gate, () =>
        {
            work();
            return Task.CompletedTask;
        });
    }

    private Task QueueAsync(SemaphoreSlim gate, Func<Task> work)
    {
        ArgumentNullException.ThrowIfNull(work);
        return Task.Run(async () =>
        {
            await gate.WaitAsync(_cts.Token).ConfigureAwait(false);
            try
            {
                await work().ConfigureAwait(false);
            }
            finally
            {
                gate.Release();
            }
        });
    }

    public void Dispose()
    {
        _cts.Cancel();
        _ioGate.Dispose();
        _cpuGate.Dispose();
        _cts.Dispose();
        GC.SuppressFinalize(this);
    }
}
