// Copyright (c) MUXUE1230. All rights reserved.
// Modifications Copyright (c) 2026 PCL N contributors.
// Licensed under the Apache License, Version 2.0.

using System;
using System.Threading;
using System.Threading.Tasks;

namespace PCL.Core.Utils.Threading;

// Partly generated by o4-mini-high (20250709)

/// <summary>
/// 可限制并发线程数量的任务池。
/// </summary>
public sealed class LimitedTaskPool : IDisposable
{
    /// <summary>
    /// 最大并发线程数。
    /// </summary>
    public int MaxThread { get; }

    private readonly SemaphoreSlim _gate;
    private readonly CancellationTokenSource _cts = new();

    /// <summary>
    /// 初始化 <see cref="LimitedTaskPool"/> 实例
    /// </summary>
    /// <param name="maxThread">参考 <see cref="MaxThread"/>，最小为 1</param>
    /// <exception cref="ArgumentOutOfRangeException"><paramref name="maxThread"/> 小于 1</exception>
    public LimitedTaskPool(int maxThread)
    {
        ArgumentOutOfRangeException.ThrowIfLessThan(maxThread, 1);

        MaxThread = maxThread;

        _gate = new SemaphoreSlim(maxThread, maxThread);
    }

    /// <summary>
    /// 提交一个任务。
    /// </summary>
    public Task Submit(Action work)
    {
        ArgumentNullException.ThrowIfNull(work);
        return Task.Run(async () =>
        {
            await _gate.WaitAsync(_cts.Token).ConfigureAwait(false);
            try
            {
                work();
            }
            finally
            {
                _gate.Release();
            }
        });
    }

    /// <summary>
    /// 提交一个异步任务。
    /// </summary>
    public Task Submit(Func<Task> work)
    {
        ArgumentNullException.ThrowIfNull(work);
        return Task.Run(async () =>
        {
            await _gate.WaitAsync(_cts.Token).ConfigureAwait(false);
            try
            {
                await work().ConfigureAwait(false);
            }
            finally
            {
                _gate.Release();
            }
        });
    }

    /// <summary>
    /// 取消所有任务。
    /// </summary>
    public void CancelAll() => _cts.Cancel();

    public void Dispose()
    {
        _cts.Cancel();
        _gate.Dispose();
        _cts.Dispose();
        GC.SuppressFinalize(this);
    }
}
