blank_issues_enabled: false
contact_links:
  - name: 主页预设反馈
    url: https://github.com/Meloong-Git/PCL2/discussions/categories/自定义主页
    about: 提交与预设的主页（设置 → 个性化 → 主页预设）中的具体内容相关的反馈
  - name: 提问 / 讨论
    url: https://github.com/MuXue1230-owo/PCL2-N/discussions/new
    about: 想问问或谈谈关于 PCL N Edition 的事情...
